version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_key:
          fingerprints:
            - "0d:a0:da:e4:e1:a7:1d:ac:19:c5:ec:22:bf:b6:6e:5a"
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build